package dev.rippleguard.audit.domain;

public enum AuditQuarantineReason {
    MALFORMED_EVENT,
    UNSUPPORTED_SCHEMA_VERSION,
    CONTRACT_VALIDATION_FAILED,
    INVALID_PRODUCER,
    BROKEN_CAUSATION,
    CONFLICTING_EVENT_PAYLOAD,
    RESULT_REFERENCE_MISMATCH,
    DUPLICATE_AGENT_RUN_CONFLICT,
    DUPLICATE_ATTEMPT_CONFLICT
}
